test:
  config: My config value PROFILE TEST 3

# Config H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    password:
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
